apiVersion: apps/v1
kind: Deployment
metadata:
  name: study-buddy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: study-buddy
  template:
    metadata:
      labels:
        app: study-buddy
    spec:
      containers:
      - name: study-buddy
        image: yash9886/study-buddy:v38
        ports:
        - containerPort: 8501
        env:
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: groq-api-secret
              key: GROQ_API_KEY
